version: '3'
services:
   jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    user: root
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/jenkins-home:/var/jenkins-home"
    networks:
      - net
   remote_host:
    container_name: remote_host
    image: remote_host
    build:
     context: centos7
    networks:
     - net
networks:
  net:
